/* eslint-disable */
/* prettier-ignore */
// 自动导入函数全局声明（手动维护，禁止自动生成覆盖）

/// <reference types="vite/client" />

declare global {
  // Vue APIs
  const EffectScope: typeof import('vue')['EffectScope']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onMounted: (callback: () => void) => import('vue').EffectLifecycleHook
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAttrs: typeof import('vue')['useAttrs']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const whenever: typeof import('vue')['whenever']
  const withDefaults: typeof import('vue')['withDefaults']
  const withDirectives: typeof import('vue')['withDirectives']
  const withMemo: typeof import('vue')['withMemo']

  // Vue types (declared as type, not const, to avoid conflicts with import type)
  type App = typeof import('vue')['App']
  type Component = typeof import('vue')['Component']
  type ComponentPublicInstance = typeof import('vue')['ComponentPublicInstance']
  type Directive = typeof import('vue')['Directive']
  type DirectiveBinding = typeof import('vue')['DirectiveBinding']
  type Ref = typeof import('vue')['Ref']
  type MaybeRef = typeof import('vue')['MaybeRef']
  type MaybeRefOrGetter = typeof import('vue')['MaybeRefOrGetter']
  type RefUnwrapBailTypes = typeof import('vue')['RefUnwrapBailTypes']
  type ShallowRef = typeof import('vue')['ShallowRef']
  type ToRef = typeof import('vue')['ToRef']
  type ToRefs = typeof import('vue')['ToRefs']
  type UnwrapRef = typeof import('vue')['UnwrapRef']
  type WritableComputedRef = typeof import('vue')['WritableComputedRef']
  type ComputedRef = typeof import('vue')['ComputedRef']
  type ReactiveEffectOptions = typeof import('vue')['ReactiveEffectOptions']
  type PropType = typeof import('vue')['PropType']
  type VNode = typeof import('vue')['VNode']
  type ExtractPropTypes = typeof import('vue')['ExtractPropTypes']
  type ExtractPublicPropTypes = typeof import('vue')['ExtractPublicPropTypes']
  type ComponentOptions = typeof import('vue')['ComponentOptions']
  type ComponentCustomProperties = typeof import('vue')['ComponentCustomProperties']
  type ComponentCustomOptions = typeof import('vue')['ComponentCustomOptions']
  type DirectiveArguments = typeof import('vue')['DirectiveArguments']

  // Element Plus
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElTree: typeof import('element-plus/es')['ElTree']

  // Pinia
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const createPinia: typeof import('pinia')['createPinia']
  const defineStore: typeof import('pinia')['defineStore']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const storeToRefs: typeof import('pinia')['storeToRefs']

  // VueUse Core
  const asyncComputed: typeof import('@vueuse/core')['asyncComputed']
  const autoResetRef: typeof import('@vueuse/core')['autoResetRef']
  const computedAsync: typeof import('@vueuse/core')['computedAsync']
  const computedEager: typeof import('@vueuse/core')['computedEager']
  const computedInject: typeof import('@vueuse/core')['computedInject']
  const computedWithControl: typeof import('@vueuse/core')['computedWithControl']
  const controlledComputed: typeof import('@vueuse/core')['controlledComputed']
  const controlledRef: typeof import('@vueuse/core')['controlledRef']
  const createEventHook: typeof import('@vueuse/core')['createEventHook']
  const createGlobalState: typeof import('@vueuse/core')['createGlobalState']
  const createInjectionState: typeof import('@vueuse/core')['createInjectionState']
  const createReactiveFn: typeof import('@vueuse/core')['createReactiveFn']
  const createReusableTemplate: typeof import('@vueuse/core')['createReusableTemplate']
  const createSharedComposable: typeof import('@vueuse/core')['createSharedComposable']
  const createTemplatePromise: typeof import('@vueuse/core')['createTemplatePromise']
  const createUnrefFn: typeof import('@vueuse/core')['createUnrefFn']
  const debouncedRef: typeof import('@vueuse/core')['debouncedRef']
  const debouncedWatch: typeof import('@vueuse/core')['debouncedWatch']
  const eagerComputed: typeof import('@vueuse/core')['eagerComputed']
  const extendRef: typeof import('@vueuse/core')['extendRef']
  const ignorableWatch: typeof import('@vueuse/core')['ignorableWatch']
  const injectLocal: typeof import('@vueuse/core')['injectLocal']
  const isDefined: typeof import('@vueuse/core')['isDefined']
  const makeDepsRef: typeof import('@vueuse/core')['makeDepsRef']
  const makeReactiveFn: typeof import('@vueuse/core')['makeReactiveFn']
  const pausableWatch: typeof import('@vueuse/core')['pausableWatch']
  const provideLocal: typeof import('@vueuse/core')['provideLocal']
  const reactify: typeof import('@vueuse/core')['reactify']
  const reactifyObject: typeof import('@vueuse/core')['reactifyObject']
  const reactiveComputed: typeof import('@vueuse/core')['reactiveComputed']
  const reactiveO: typeof import('@vueuse/core')['reactiveO']
  const reactiveRef: typeof import('@vueuse/core')['reactiveRef']
  const refAuto: typeof import('@vueuse/core')['refAuto']
  const refCached: typeof import('@vueuse/core')['refCached']
  const refElement: typeof import('@vueuse/core')['refElement']
  const refInBoolean: typeof import('@vueuse/core')['refInBoolean']
  const refInject: typeof import('@vueuse/core')['refInject']
  const refLocal: typeof import('@vueuse/core')['refLocal']
  const refN: typeof import('@vueuse/core')['refN']
  const refThrottled: typeof import('@vueuse/core')['refThrottled']
  const refWithControl: typeof import('@vueuse/core')['refWithControl']
  const resolveInject: typeof import('@vueuse/core')['resolveInject']
  const resolveRef: typeof import('@vueuse/core')['resolveRef']
  const resolveTyped: typeof import('@vueuse/core')['resolveTyped']
  const setRef: typeof import('@vueuse/core')['setRef']
  const templateRef: typeof import('@vueuse/core')['templateRef']
  const toReactive: typeof import('@vueuse/core')['toReactive']
  const transformRef: typeof import('@vueuse/core')['transformRef']
  const tryOnBeforeMount: typeof import('@vueuse/core')['tryOnBeforeMount']
  const tryOnBeforeUnmount: typeof import('@vueuse/core')['tryOnBeforeUnmount']
  const tryOnMounted: typeof import('@vueuse/core')['tryOnMounted']
  const tryOnUnmounted: typeof import('@vueuse/core')['tryOnUnmounted']
  const typeName: typeof import('@vueuse/core')['typeName']
  const useActiveElement: typeof import('@vueuse/core')['useActiveElement']
  const useArray: typeof import('@vueuse/core')['useArray']
  const useAsyncState: typeof import('@vueuse/core')['useAsyncState']
  const useBase64: typeof import('@vueuse/core')['useBase64']
  const useBeforeLeave: typeof import('@vueuse/core')['useBeforeLeave']
  const useBreakpoint: typeof import('@vueuse/core')['useBreakpoint']
  const useBroadcastChannel: typeof import('@vueuse/core')['useBroadcastChannel']
  const useBrowserLocation: typeof import('@vueuse/core')['useBrowserLocation']
  const useCached: typeof import('@vueuse/core')['useCached']
  const useCeiling: typeof import('@vueuse/core')['useCeiling']
  const useClipboard: typeof import('@vueuse/core')['useClipboard']
  const useCloned: typeof import('@vueuse/core')['useCloned']
  const useColorMode: typeof import('@vueuse/core')['useColorMode']
  const useConfirmDialog: typeof import('@vueuse/core')['useConfirmDialog']
  const useCounter: typeof import('@vueuse/core')['useCounter']
  const useCssVar: typeof import('@vueuse/core')['useCssVar']
  const useCurrentElement: typeof import('@vueuse/core')['useCurrentElement']
  const useCycleList: typeof import('@vueuse/core')['useCycleList']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useDateFormat: typeof import('@vueuse/core')['useDateFormat']
  const useDebounce: typeof import('@vueuse/core')['useDebounce']
  const useDebounceFn: typeof import('@vueuse/core')['useDebounceFn']
  const useDefault: typeof import('@vueuse/core')['useDefault']
  const useDisplayMedia: typeof import('@vueuse/core')['useDisplayMedia']
  const useDocumentVisibility: typeof import('@vueuse/core')['useDocumentVisibility']
  const useDraggable: typeof import('@vueuse/core')['useDraggable']
  const useDropZone: typeof import('@vueuse/core')['useDropZone']
  const useElementBounding: typeof import('@vueuse/core')['useElementBounding']
  const useElementByPointer: typeof import('@vueuse/core')['useElementByPointer']
  const useElementHover: typeof import('@vueuse/core')['useElementHover']
  const useElementSize: typeof import('@vueuse/core')['useElementSize']
  const useElementVisibility: typeof import('@vueuse/core')['useElementVisibility']
  const useEventBus: typeof import('@vueuse/core')['useEventBus']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useEyeDropper: typeof import('@vueuse/core')['useEyeDropper']
  const useFavicon: typeof import('@vueuse/core')['useFavicon']
  const useFetch: typeof import('@vueuse/core')['useFetch']
  const useFileDialog: typeof import('@vueuse/core')['useFileDialog']
  const useFileSystemAccess: typeof import('@vueuse/core')['useFileSystemAccess']
  const useFocus: typeof import('@vueuse/core')['useFocus']
  const useFocusWithin: typeof import('@vueuse/core')['useFocusWithin']
  const useFps: typeof import('@vueuse/core')['useFps']
  const useFullscreen: typeof import('@vueuse/core')['useFullscreen']
  const useGeolocation: typeof import('@vueuse/core')['useGeolocation']
  const useHasOwn: typeof import('@vueuse/core')['useHasOwn']
  const useHead: typeof import('@vueuse/core')['useHead']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useIntersectionObserver: typeof import('@vueuse/core')['useIntersectionObserver']
  const useInterval: typeof import('@vueuse/core')['useInterval']
  const useIntervalFn: typeof import('@vueuse/core')['useIntervalFn']
  const useKeyModifier: typeof import('@vueuse/core')['useKeyModifier']
  const useLastChanged: typeof import('@vueuse/core')['useLastChanged']
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage']
  const useMagicKeys: typeof import('@vueuse/core')['useMagicKeys']
  const useManualRefHistory: typeof import('@vueuse/core')['useManualRefHistory']
  const useMediaQuery: typeof import('@vueuse/core')['useMediaQuery']
  const useMemo: typeof import('@vueuse/core')['useMemo']
  const useMemory: typeof import('@vueuse/core')['useMemory']
  const useMounted: typeof import('@vueuse/core')['useMounted']
  const useMouse: typeof import('@vueuse/core')['useMouse']
  const useMouseInElement: typeof import('@vueuse/core')['useMouseInElement']
  const useMousePressed: typeof import('@vueuse/core')['useMousePressed']
  const useMutationObserver: typeof import('@vueuse/core')['useMutationObserver']
  const useNavigator: typeof import('@vueuse/core')['useNavigator']
  const useNetwork: typeof import('@vueuse/core')['useNetwork']
  const useNow: typeof import('@vueuse/core')['useNow']
  const useObjectUrl: typeof import('@vueuse/core')['useObjectUrl']
  const useOffsetPagination: typeof import('@vueuse/core')['useOffsetPagination']
  const useOnline: typeof import('@vueuse/core')['useOnline']
  const usePageLeave: typeof import('@vueuse/core')['usePageLeave']
  const usePan: typeof import('@vueuse/core')['usePan']
  const useParam: typeof import('@vueuse/core')['useParam']
  const useParent: typeof import('@vueuse/core')['useParent']
  const usePassiveWatch: typeof import('@vueuse/core')['usePassiveWatch']
  const usePeak: typeof import('@vueuse/core')['usePeak']
  const usePermission: typeof import('@vueuse/core')['usePermission']
  const usePinia: typeof import('@vueuse/core')['usePinia']
  const usePointer: typeof import('@vueuse/core')['usePointer']
  const usePointerLock: typeof import('@vueuse/core')['usePointerLock']
  const usePointerSwipe: typeof import('@vueuse/core')['usePointerSwipe']
  const usePreferredColorScheme: typeof import('@vueuse/core')['usePreferredColorScheme']
  const usePreferredContrast: typeof import('@vueuse/core')['usePreferredContrast']
  const usePreferredDark: typeof import('@vueuse/core')['usePreferredDark']
  const usePreferredLanguages: typeof import('@vueuse/core')['usePreferredLanguages']
  const usePreferredReducedMotion: typeof import('@vueuse/core')['usePreferredReducedMotion']
  const usePrint: typeof import('@vueuse/core')['usePrint']
  const useProjection: typeof import('@vueuse/core')['useProjection']
  const useProvide: typeof import('@vueuse/core')['useProvide']
  const useProvideLocal: typeof import('@vueuse/core')['useProvideLocal']
  const useQuantum: typeof import('@vueuse/core')['useQuantum']
  const useRaf: typeof import('@vueuse/core')['useRaf']
  const useRafFn: typeof import('@vueuse/core')['useRafFn']
  const useRefHistory: typeof import('@vueuse/core')['useRefHistory']
  const useRelativeLuminance: typeof import('@vueuse/core')['useRelativeLuminance']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useRound: typeof import('@vueuse/core')['useRound']
  const useRouter: typeof import('vue-router')['useRouter']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRuleQueue: typeof import('@vueuse/core')['useRuleQueue']
  const useScreenOrientation: typeof import('@vueuse/core')['useScreenOrientation']
  const useScreenSafeArea: typeof import('@vueuse/core')['useScreenSafeArea']
  const useScriptTag: typeof import('@vueuse/core')['useScriptTag']
  const useScroll: typeof import('@vueuse/core')['useScroll']
  const useScrollLock: typeof import('@vueuse/core')['useScrollLock']
  const useSessionStorage: typeof import('@vueuse/core')['useSessionStorage']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useSpeechSynthesis: typeof import('@vueuse/core')['useSpeechSynthesis']
  const useSpeechRecognition: typeof import('@vueuse/core')['useSpeechRecognition']
  const useSquare: typeof import('@vueuse/core')['useSquare']
  const useState: typeof import('@vueuse/core')['useState']
  const useStepper: typeof import('@vueuse/core')['useStepper']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useStorageAsync: typeof import('@vueuse/core')['useStorageAsync']
  const useStyleTag: typeof import('@vueuse/core')['useStyleTag']
  const useSupported: typeof import('@vueuse/core')['useSupported']
  const useSwipe: typeof import('@vueuse/core')['useSwipe']
  const useTarget: typeof import('@vueuse/core')['useTarget']
  const useTextareaAutoHeight: typeof import('@vueuse/core')['useTextareaAutoHeight']
  const useTextContent: typeof import('@vueuse/core')['useTextContent']
  const useTextDirection: typeof import('@vueuse/core')['useTextDirection']
  const useTextSelection: typeof import('@vueuse/core')['useTextSelection']
  const useTextTrim: typeof import('@vueuse/core')['useTextTrim']
  const useTheme: typeof import('@vueuse/core')['useTheme']
  const useThrottle: typeof import('@vueuse/core')['useThrottle']
  const useThrottleFn: typeof import('@vueuse/core')['useThrottleFn']
  const useTimeAgo: typeof import('@vueuse/core')['useTimeAgo']
  const useTimeout: typeof import('@vueuse/core')['useTimeout']
  const useTimeoutFn: typeof import('@vueuse/core')['useTimeoutFn']
  const useTimer: typeof import('@vueuse/core')['useTimer']
  const useTimestamp: typeof import('@vueuse/core')['useTimestamp']
  const useTo: typeof import('@vueuse/core')['useTo']
  const useToNumber: typeof import('@vueuse/core')['useToNumber']
  const useToString: typeof import('@vueuse/core')['useToString']
  const useToggle: typeof import('@vueuse/core')['useToggle']
  const useTouch: typeof import('@vueuse/core')['useTouch']
  const useTransition: typeof import('@vueuse/core')['useTransition']
  const useTruncate: typeof import('@vueuse/core')['useTruncate']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']
  const useUse: typeof import('@vueuse/core')['useUse']
  const useV5Counter: typeof import('@vueuse/core')['useV5Counter']
  const useVibrate: typeof import('@vueuse/core')['useVibrate']
  const useVirtualList: typeof import('@vueuse/core')['useVirtualList']
  const useVision: typeof import('@vueuse/core')['useVision']
  const useVisualElement: typeof import('@vueuse/core')['useVisualElement']
  const useVModel: typeof import('@vueuse/core')['useVModel']
  const useVueRouter: typeof import('@vueuse/core')['useVueRouter']
  const useWakeLock: typeof import('@vueuse/core')['useWakeLock']
  const useWebSocket: typeof import('@vueuse/core')['useWebSocket']
  const useWebWorker: typeof import('@vueuse/core')['useWebWorker']
  const useWebWorkerFn: typeof import('@vueuse/core')['useWebWorkerFn']
  const useWindowFocus: typeof import('@vueuse/core')['useWindowFocus']
  const useWindowScroll: typeof import('@vueuse/core')['useWindowScroll']
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize']
  const useZoom: typeof import('@vueuse/core')['useZoom']
  const useZone: typeof import('@vueuse/core')['useZone']
  const vModel: typeof import('@vueuse/core')['vModel']
  const vModelText: typeof import('@vueuse/core')['vModelText']
  const watchArray: typeof import('@vueuse/core')['watchArray']
  const watchAtMost: typeof import('@vueuse/core')['watchAtMost']
  const watchDebounced: typeof import('@vueuse/core')['watchDebounced']
  const watchIgnorable: typeof import('@vueuse/core')['watchIgnorable']
  const watchImmediate: typeof import('@vueuse/core')['watchImmediate']
  const watchInFocus: typeof import('@vueuse/core')['watchInFocus']
  const watchOnce: typeof import('@vueuse/core')['watchOnce']
  const watchThrottled: typeof import('@vueuse/core')['watchThrottled']
  const watchTriggerable: typeof import('@vueuse/core')['watchTriggerable']
  const watchWithFilter: typeof import('@vueuse/core')['watchWithFilter']
  const whichBrowser: typeof import('@vueuse/core')['whichBrowser']
  const withIntersectionObserver: typeof import('@vueuse/core')['withIntersectionObserver']
  const withLatestFrom: typeof import('@vueuse/core')['withLatestFrom']
  const withMounted: typeof import('@vueuse/core')['withMounted']
  const withParams: typeof import('@vueuse/core')['withParams']
  const withPromise: typeof import('@vueuse/core')['withPromise']
  const withRef: typeof import('@vueuse/core')['withRef']
  const withRetry: typeof import('@vueuse/core')['withRetry']
  const withTiming: typeof import('@vueuse/core')['withTiming']
  const withTransition: typeof import('@vueuse/core')['withTransition']
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside']
  const useElementRef: typeof import('@vueuse/core')['useElementRef']
}

export {}
